version: "3.9"

services:

  hms:
    image: "ghcr.io/trinodb/testing/hive3.1-hive:latest"
    ports:
      - "9083:9083"
      - "3306:53306"
    expose:
      - "3306"
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  hms-db:
    image: "mysql:8.0.18"
    ports:
      - "3306:53306"
    expose:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  hms-thrift:
    build:
      context: hms-thrift
      dockerfile: Dockerfile
      args:
        - JAVA_VERSION=${JAVA_VERSION:-17}
        - HADOOP_VERSION=${HADOOP_VERSION:-3.1.2}
        - HIVE_VERSION=${HIVE_VERSION:-3.1.2}
        - GCS_CONNECTOR_VERSION=${GCS_CONNECTOR_VERSION:-hadoop3-latest}
    image: hms-thrift:${HIVE_VERSION:-3.1.2}
    ports:
      - "9083:9083"
    depends_on:
      - hms-db
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GCS_ACCOUNT_EMAIL=${GCS_ACCOUNT_EMAIL}
      - GCS_PRIVATE_KEY_ID=${GCS_PRIVATE_KEY_ID}
      - GCS_PRIVATE_KEY=${GCS_PRIVATE_KEY}
      - HMS_DB_HOST=${HMS_DB_HOST:-hms-db}
      - HMS_DB_PORT=${HMS_DB_PORT:-3306}
      - HMS_DB_NAME=${HMS_DB_NAME:-hms}
      - HMS_DB_USER=${HMS_DB_USER:-root}
      - HMS_DB_PASSWORD=${HMS_DB_PASSWORD:-}
      - HMS_DEBUG=${DEBUG:-false}

  conn-pg12:
    image: "postgres:12"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgresConnector123
      - POSTGRES_HOST_AUTH_METHOD=trust

  coordinator:
    build:
      context: server
      dockerfile: Dockerfile
      network: host
      args:
        - TRINO_VERSION=${TRINO_VERSION:-394}
        - JAVA_VERSION=${JAVA_VERSION:-17}
    image: trino-server:${TRINO_VERSION:-394}
    ports:
      - "8080:8080"
    environment:
      - IS_COORDINATOR=true
      - COORDINATOR_IS_WORKER=${COORDINATOR_IS_WORKER}
      - HMS_ADDRESS=${HMS_ADDRESS:-hms-thrift}
      - HMS_THRIFT_PORT=${HMS_THRIFT_PORT:-9083}
      - HMS_JDBC_URL=jdbc:mysql://${HMS_DB_HOST-hms-db}:${HMS_DB_PORT-3306}?zeroDateTimeBehavior=convertToNull&useSSL=false
      - HMS_DB_USER=${HMS_DB_USER:-root}
      - HMS_DB_PASSWORD=${HMS_DB_PASSWORD:-}
      - HIVE_SECURITY=${HIVE_SECURITY:-legacy}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GCS_ACCOUNT_EMAIL=${GCS_ACCOUNT_EMAIL}
      - GCS_PRIVATE_KEY_ID=${GCS_PRIVATE_KEY_ID}
      - GCS_PRIVATE_KEY=${GCS_PRIVATE_KEY}
      - GCS_PROJECT_ID=${GCS_PROJECT_ID}
      - GCS_CLIENT_ID=${GCS_CLIENT_ID}
      - DEBUG=${DEBUG:-false}

  worker:
    build:
      context: server
      dockerfile: Dockerfile
      args:
        - TRINO_VERSION=${TRINO_VERSION:-394}
    image: trino-server:${TRINO_VERSION:-394}
    environment:
      - IS_COORDINATOR=false
      - COORDINATOR_IS_WORKER=${COORDINATOR_IS_WORKER}
      - HMS_ADDRESS=${HMS_ADDRESS:-hms-thrift}
      - HMS_THRIFT_PORT=${HMS_THRIFT_PORT:-9083}
      - HMS_JDBC_URL=jdbc:mysql://${HMS_DB_HOST-hms-db}:${HMS_DB_PORT-3306}?zeroDateTimeBehavior=convertToNull&useSSL=false
      - HMS_DB_USER=${HMS_DB_USER:-root}
      - HMS_DB_PASSWORD=${HMS_DB_PASSWORD:-}
      - HIVE_SECURITY=${HIVE_SECURITY:-legacy}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GCS_ACCOUNT_EMAIL=${GCS_ACCOUNT_EMAIL}
      - GCS_PRIVATE_KEY_ID=${GCS_PRIVATE_KEY_ID}
      - GCS_PRIVATE_KEY=${GCS_PRIVATE_KEY}
      - GCS_PROJECT_ID=${GCS_PROJECT_ID}
      - GCS_CLIENT_ID=${GCS_CLIENT_ID}
      - DEBUG=${DEBUG:-false}
